name: robing
favicon: null
layout_spectrum: 0.4508082689717412
typography_spectrum: 0.08709017932415009
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.21084603085182607
  lightness: 0.576397986151278
  saturation: 0.28853129921481013
  rhythmicContrast: 0.32640068558976054
purpose: []
